spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:rbsndev}:${DB_PASSWORD}@cluster0.akefvzi.mongodb.net/${DB_NAME:webflux}?retryWrites=true&w=majority
      auto-index-creation: true
  application:
    name: spring-webflux